version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress1
      - wordpress2

  wordpress1:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: cangrow
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db

  wordpress2:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: cangrow
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: cangorw
      MYSQL_PASSWORD: 123
