version: '3'

services:
  proxysql:
    image: proxysql/proxysql
    container_name: proxysql_cangrow
    ports:
      - "6032:6032"
      - "6033:6033"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql/proxysql.cnf
      - ./proxysql/initial.sh:/etc/proxysql/initial.sh
    depends_on:
      - mariadb_master
      - mariadb_replica
      - nginx
    networks:
      - cangrownet
  mariadb_master:
    image: mariadb:latest
    container_name: master_cangrow
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=${MYSQL_DATABASE} --binlog-format=mixed
    volumes:
      - mariadb_master_data:/var/lib/mysql
      - ./masterdb:/docker-entrypoint-initdb.d
    networks:
      - cangrownet

  mariadb_replica:
    image: mariadb:latest
    container_name: replica_cangrow
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --replicate-do-db=${MYSQL_DATABASE} --server-id=2 --log-bin=mysql-bin --binlog-do-db=${MYSQL_DATABASE}
    depends_on:
      - mariadb_master
    volumes:
      - mariadb_replica_data:/var/lib/mysql
      - ./replicadb:/docker-entrypoint-initdb.d
    networks:
      - cangrownet

  nginx:
    image: nginx:latest
    container_name: nginx_cangrow
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - wordpress1
      - wordpress2
    networks:
      - cangrownet

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1_cangrow
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb_replica
    networks:
      - cangrownet

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2_cangrow
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb_replica
      - wordpress1
    networks:
      - cangrownet
        # db:
  #   image: mariadb:latest
  #   container_name: mariadb_cangrow
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   networks:
  #     - cangrownet


networks:
  cangrownet:
    ipam:
      config:
        - subnet: 172.28.0.0/28

volumes:
  wordpress_data:
  mariadb_master_data:
  mariadb_replica_data:

