name: Deploy WordPress Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync theme directory to server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: '185.240.151.70'
          REMOTE_PORT: '22'
          REMOTE_USER: 'debian'
          ARGS: '-avzr --delete'
          SOURCE: 'themes/'
          TARGET: '/var/lib/docker/volumes/wordpress_data/_data/wp-content/themes'
