name: Deploy WordPress Theme

on:
  push:
    branches:
      - main
    paths:
      - 'themes/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: 'ftp://185.240.151.70'
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './themes/'
          server-dir: '/var/lib/docker/volumes/wordpress_data/_data/wp-content/themes/'

