name: Deploy WordPress Theme

on:
  push:
    branches:
      - main
    paths:
      - 'themes/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync theme directory to server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          ARGS: '-avzr --delete'
          SOURCE: 'themes/'
          TARGET: '/var/lib/docker/volumes/wordpress_data/_data/wp-content/themes'

