name: Deploy WordPress Theme with Custom DNS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Set custom DNS in resolv.conf
        run: |
          echo "nameserver 178.22.122.100" | sudo tee /etc/resolv.conf > /dev/null
          echo "nameserver 185.51.200.2" | sudo tee -a /etc/resolv.conf > /dev/null

      - name: Sync theme directory to server
        uses: easingthemes/ssh-deploy@v3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: '185.240.151.70'
          REMOTE_PORT: '22'
          REMOTE_USER: 'debian'
          ARGS: '-avzr --delete'
          SOURCE: 'themes/'
          TARGET: '/var/lib/docker/volumes/wordpress_data/_data/wp-content/themes/'

