name: Deploy WordPress Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      dns:
        image: cloudflare/cloudflared:latest
        ports:
          - 53:53/tcp
          - 53:53/udp
    env:
      HTTP_PROXY: 'http://free.shecan.ir/dns-query'
      HTTPS_PROXY: 'https://free.shecan.ir/dns-query'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up DNS over TLS
        run: |
          echo "nameserver 127.0.0.1" | sudo tee /etc/resolv.conf > /dev/null
          sudo cloudflared proxy-dns --upstream https://free.shecan.ir/dns-query

      - name: Sync theme directory to server
        uses: easingthemes/ssh-deploy@v3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: '185.240.151.70'
          REMOTE_PORT: '22'
          REMOTE_USER: 'debian'
          ARGS: '-avzr --delete'
          SOURCE: 'themes/'
          TARGET: '/var/lib/docker/volumes/wordpress_data/_data/wp-content/themes/'

