name: Deploy WordPress Theme with Custom DNS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Stop and disable systemd-resolved
        run: |
          sudo systemctl stop systemd-resolved
          sudo systemctl disable systemd-resolved

      - name: Start DNS server
        run: |
          docker run --name my-dns-server -d -p 178.22.122.100:53:53/udp -p 178.22.122.100:53:53/tcp andyshinn/dnsmasq:2.78
          # Set up your custom DNS settings here

      - name: Set custom DNS for the runner
        run: |
          echo "nameserver <YOU-EXTERNAL-IP>" | sudo tee /etc/resolv.conf > /dev/null

      - name: Sync theme directory to server
        uses: easingthemes/ssh-deploy@v3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: '185.240.151.70'
          REMOTE_PORT: '22'
          REMOTE_USER: 'debian'
          ARGS: '-avzr --delete'
          SOURCE: 'themes/'
          TARGET: '/var/lib/docker/volumes/wordpress_data/_data/wp-content/themes/'

